TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE
#=============================

PROD_IOC_Linux += URLTest
PROD_IOC_WIN32 += URLTest
PROD_IOC_cygwin32 += URLTest

# Add locally compiled object code
PROD_SRCS += URLTest

include $(TOP)/ADApp/commonDriverMakefile

#=============================

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

